apiVersion: v1
kind: Pod
metadata:
  name: debug-pod-a100
spec:
  restartPolicy: Never
  containers:
  - name: debug
    image: ubuntu:22.04
    command: ["sleep", "3600"]
    volumeMounts:
    - name: storage
      mountPath: /workspace/storage_a100
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: v2v-diffuser-kuntal-a100
