apiVersion: v1
kind: Pod
metadata:
  name: v2v-diffusion-interactive
  labels:
    app: v2v-diffusion
    type: interactive
spec:
  restartPolicy: Never

  containers:
  - name: training
    image: ghcr.io/kkuntal990/v2v-diffusion:latest
    imagePullPolicy: Always

    command: ["/bin/bash"]
    args:
      - "-c"
      - |
        echo "Container ready! All dependencies pre-installed."
        echo "Working directory: /workspace"

        echo "Setup complete! Keeping container alive..."
        sleep 3600

    resources:
      requests:
        memory: "8Gi"
        cpu: "2"
        nvidia.com/gpu: "1"
      limits:
        memory: "32Gi"
        cpu: "8"
        nvidia.com/gpu: "1"

    volumeMounts:
    - name: storage
      mountPath: /workspace/storage
    - name: dshm
      mountPath: /dev/shm

    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: TORCH_HOME
      value: "/workspace/storage/.cache/torch"
    - name: HF_HOME
      value: "/workspace/storage/.cache/huggingface"

  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: v2v-diffuser-kuntal
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: "8Gi"

  # No nodeSelector - will use any available GPU node
