apiVersion: v1
kind: Pod
metadata:
  name: v2v-diffusion-interactive
  labels:
    app: v2v-diffusion
    type: interactive
spec:
  restartPolicy: Never

  containers:
  - name: training
    image: pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
    imagePullPolicy: IfNotPresent

    command: ["/bin/bash"]
    args:
      - "-c"
      - |
        echo "Installing system dependencies..."
        apt-get update && apt-get install -y git wget && rm -rf /var/lib/apt/lists/*

        echo "Cloning repository..."
        cd /workspace
        if [ ! -d "video-to-video-diffusion" ]; then
          git clone https://github.com/Kkuntal990/video-to-video-diffusion.git
        fi
        cd video-to-video-diffusion
        git checkout pretrained_main
        git pull

        echo "Installing Python dependencies..."
        pip install --no-cache-dir -r requirements.txt

        echo "Setup complete! Keeping container alive..."
        sleep infinity

    resources:
      requests:
        memory: "32Gi"
        cpu: "8"
        nvidia.com/gpu: "1"
      limits:
        memory: "64Gi"
        cpu: "16"
        nvidia.com/gpu: "1"

    volumeMounts:
    - name: storage
      mountPath: /workspace/storage
    - name: dshm
      mountPath: /dev/shm

    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: TORCH_HOME
      value: "/workspace/storage/.cache/torch"
    - name: HF_HOME
      value: "/workspace/storage/.cache/huggingface"

  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: v2v-diffuser-kuntal
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: "8Gi"

  # Node selector for GPU nodes
  nodeSelector:
    nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB  # Adjust based on available GPUs
