apiVersion: batch/v1
kind: Job
metadata:
  name: v2v-patch-evaluation
spec:
  ttlSecondsAfterFinished: 3600  # Keep job for 6 hours after completion
  template:
    metadata:
      labels:
        app: v2v-patch-evaluation
        type: inference-job
        gpu: a100
    spec:
      restartPolicy: Never
      containers:
      - name: patch-eval
        image: kuntalkokate/llm_agent_v2v_train:latest
        command:
          - /bin/bash
          - -c
          - |
            echo "Starting Patch Evaluation..."
            echo "GPU Info:"
            nvidia-smi
            echo ""
            echo "Node: $(hostname)"
            echo ""

            # Find latest checkpoint automatically
            CHECKPOINT_DIR="/workspace/storage_a100/checkpoints/slice_interp_full_medium"
            LATEST_CHECKPOINT=$(ls -t ${CHECKPOINT_DIR}/checkpoint_best_epoch_*_slice_interp_full3.pt 2>/dev/null | head -1)

            if [ -z "$LATEST_CHECKPOINT" ]; then
              echo "ERROR: No checkpoint found in ${CHECKPOINT_DIR}"
              echo "Available files:"
              ls -lh ${CHECKPOINT_DIR}/
              exit 1
            fi

            echo "Using checkpoint: ${LATEST_CHECKPOINT}"
            echo ""

            # Run patch evaluation
            python scripts/evaluate_and_visualize_patches.py \
              --checkpoint "${LATEST_CHECKPOINT}" \
              --config config/slice_interpolation_full_medium.yaml \
              --split val \
              --num-samples 50 \
              --num-inference-steps 20 \
              --sampler ddim \
              --output-dir /workspace/storage_a100/results/patch_evaluation \
              --save-predictions

            echo ""
            echo "Patch evaluation completed!"
            echo "Results saved to: /workspace/storage_a100/results/patch_evaluation"
            echo ""
            echo "Summary:"
            cat /workspace/storage_a100/results/patch_evaluation/metrics/patch_metrics.json | grep -A 10 '"overall"'

        resources:
          requests:
            memory: "16Gi"  # Increased for A100 80GB with 24 frames
            cpu: "4"
            nvidia.com/a100: "1"
          limits:
            memory: "16Gi"  # A100 80GB GPU
            cpu: "4"
            nvidia.com/a100: "1"

        volumeMounts:
        - name: storage
          mountPath: /workspace/storage_a100
        - name: dshm
          mountPath: /dev/shm

        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TORCH_HOME
          value: "/workspace/storage_a100/.cache/torch"
        - name: HF_HOME
          value: "/workspace/storage_a100/.cache/huggingface"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: HF_TOKEN
        # Memory optimization: Enable expandable CUDA memory segments
        - name: PYTORCH_CUDA_ALLOC_CONF
          value: "expandable_segments:True"

      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: v2v-diffuser-kuntal-a100-shared
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "8Gi"

      # Tolerations for A100 GPU nodes
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/hardware
        operator: Equal
        value: large-gpu
      - effect: PreferNoSchedule
        key: nvidia.com/gpu
        operator: Exists

      # Node affinity to ensure 80GB A100 (not 40GB)
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A100-SXM4-80GB
