apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: v2v-diffuser-kuntal
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
