apiVersion: v1
kind: Pod
metadata:
  name: v2v-diffusion-training-pod
  labels:
    app: v2v-diffusion
    type: training-pod
spec:
  restartPolicy: Never

  containers:
  - name: training
    image: kkokate990/v2v-diffusion:latest  # Replace with your Docker image
    imagePullPolicy: Always

    # Training command
    command: ["/bin/bash"]
    args:
      - "-c"
      - |
        echo "Starting training..."
        echo "GPU Info:"
        nvidia-smi

        # Change to working directory
        cd /workspace

        # Run training with cloud config
        python train.py --config config/cloud_train_config.yaml

        echo "Training completed!"

    resources:
      requests:
        memory: "48Gi"
        cpu: "12"
        nvidia.com/gpu: "1"
      limits:
        memory: "64Gi"
        cpu: "16"
        nvidia.com/gpu: "1"

    volumeMounts:
    - name: storage
      mountPath: /workspace/storage
    - name: dshm
      mountPath: /dev/shm

    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: TORCH_HOME
      value: "/workspace/storage/.cache/torch"
    - name: HF_HOME
      value: "/workspace/storage/.cache/huggingface"
    - name: CUDA_VISIBLE_DEVICES
      value: "0"

  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: v2v-diffuser-kuntal
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: "16Gi"

  # Node selector for GPU nodes
  nodeSelector:
    nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB  # Adjust based on available GPUs
