apiVersion: batch/v1
kind: Job
metadata:
  name: v2v-diffusion-inference-job
spec:
  template:
    metadata:
      labels:
        app: v2v-diffusion
        type: inference-job
    spec:
      restartPolicy: Never

      containers:
      - name: inference
        image: ghcr.io/kkuntal990/v2v-diffusion:latest
        imagePullPolicy: Always

        # Training command
        command: ["/bin/bash"]
        args:
        - "-c"
        - |
          echo "Starting inference job"
          echo ""
          echo "Node: $(hostname)"
          echo ""

          sleep 3600

          echo "Training completed!"

        resources:
          requests:
            memory: "16Gi"  # Increased for A100 80GB with 24 frames
            cpu: "2"
            nvidia.com/a100: "0"
          limits:
            memory: "16Gi"  # A100 80GB GPU
            cpu: "2"
            nvidia.com/a100: "0"

        volumeMounts:
        - name: storage
          mountPath: /workspace/storage_a100  # A100 storage
        - name: dshm
          mountPath: /dev/shm

        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TORCH_HOME
          value: "/workspace/storage_a100/.cache/torch"
        - name: HF_HOME
          value: "/workspace/storage_a100/.cache/huggingface"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: HF_TOKEN

      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: v2v-diffuser-kuntal-a100  # A100 storage