apiVersion: v1
kind: Pod
metadata:
  name: v2v-diffusion-training-pod
  labels:
    app: v2v-diffusion
    type: training-pod
spec:
  restartPolicy: Never

  containers:
  - name: training
    image: ghcr.io/kkuntal990/v2v-diffusion:latest
    imagePullPolicy: Always

    # Training command
    command: ["/bin/bash"]
    args:
      - "-c"
      - |
        echo "Starting training..."
        echo "GPU Info:"
        nvidia-smi

        # Run training with cloud config
        python train.py --config config/cloud_train_config.yaml

        echo "Training completed!"

    resources:
      requests:
        memory: "32Gi"
        cpu: "8"
        nvidia.com/gpu: "1"
      limits:
        memory: "32Gi"
        cpu: "16"
        nvidia.com/gpu: "1"

    volumeMounts:
    - name: storage
      mountPath: /workspace/storage
    - name: dshm
      mountPath: /dev/shm

    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: TORCH_HOME
      value: "/workspace/storage/.cache/torch"
    - name: HF_HOME
      value: "/workspace/storage/.cache/huggingface"

  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: v2v-diffuser-kuntal
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: "16Gi"

  # Node selector for GPU nodes
  nodeSelector:
    nvidia.com/gpu.product: Tesla-V100-SXM2-32GB
