apiVersion: batch/v1
kind: Job
metadata:
  name: vae-training-resume-job-a100
spec:
  template:
    metadata:
      labels:
        app: v2v-diffusion
        type: training-job
        gpu: a100
    spec:
      restartPolicy: Never

      containers:
      - name: vae-training-resume
        image: ghcr.io/kkuntal990/v2v-diffusion:latest
        imagePullPolicy: Always

        # VAE training resume command
        command: ["/bin/bash"]
        args:
        - "-c"
        - |
          echo "=========================================="
          echo "Resuming VAE Training on A100 80GB"
          echo "=========================================="
          echo "GPU Info:"
          nvidia-smi
          echo ""
          echo "Node: $(hostname)"
          echo ""

          # Check if checkpoint exists
          CHECKPOINT_PATH="/workspace/storage_a100/checkpoints/vae_training/vae_best.pt"
          if [ -f "$CHECKPOINT_PATH" ]; then
            echo "✓ Found checkpoint: $CHECKPOINT_PATH"
            echo ""
          else
            echo "✗ ERROR: Checkpoint not found at $CHECKPOINT_PATH"
            echo "Available checkpoints:"
            ls -lh /workspace/storage_a100/checkpoints/vae_training/ 2>/dev/null || echo "  (checkpoint directory not found)"
            exit 1
          fi

          # Resume training from best checkpoint
          python train_vae.py \
            --config config/vae_training.yaml \
            --resume "$CHECKPOINT_PATH"

          echo ""
          echo "=========================================="
          echo "VAE training resumed and completed!"
          echo "=========================================="

        resources:
          requests:
            memory: "32Gi"  # Increased for A100 80GB with 24 frames
            cpu: "4"
            nvidia.com/a100: "1"
          limits:
            memory: "32Gi"  # A100 80GB GPU
            cpu: "4"
            nvidia.com/a100: "1"

        volumeMounts:
        - name: storage
          mountPath: /workspace/storage_a100
        - name: dshm
          mountPath: /dev/shm

        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TORCH_HOME
          value: "/workspace/storage_a100/.cache/torch"
        - name: HF_HOME
          value: "/workspace/storage_a100/.cache/huggingface"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: HF_TOKEN

      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: v2v-diffuser-kuntal-a100-shared
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "16Gi"

      # Tolerations for A100 GPU nodes
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/hardware
        operator: Equal
        value: large-gpu
      - effect: PreferNoSchedule
        key: nvidia.com/gpu
        operator: Exists

      # Node affinity to ensure 80GB A100 (not 40GB)
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A100-SXM4-80GB
