apiVersion: batch/v1
kind: Job
metadata:
  name: vae-reconstruction-test-job
spec:
  template:
    metadata:
      labels:
        app: v2v-diffusion
        type: vae-test-job
        gpu: v100
    spec:
      restartPolicy: Never

      containers:
      - name: vae-test
        image: ghcr.io/kkuntal990/v2v-diffusion:latest
        imagePullPolicy: Always

        # VAE test command
        command: ["/bin/bash"]
        args:
        - "-c"
        - |
          echo "Starting VAE reconstruction tests on V100..."
          echo "GPU Info:"
          nvidia-smi
          echo ""
          echo "Node: $(hostname)"
          echo ""

          # Run VAE reconstruction tests
          cd /workspace
          python tests/test_vae_reconstruction.py

          echo "VAE tests completed!"

        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
            nvidia.com/gpu: "1"
          limits:
            memory: "16Gi"
            cpu: "4"
            nvidia.com/gpu: "1"

        volumeMounts:
        - name: storage
          mountPath: /workspace/storage_a100
        - name: dshm
          mountPath: /dev/shm

        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TORCH_HOME
          value: "/workspace/storage_a100/.cache/torch"
        - name: HF_HOME
          value: "/workspace/storage_a100/.cache/huggingface"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: HF_TOKEN

      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: v2v-diffuser-kuntal-a100
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "8Gi"

      # Tolerations for GPU nodes
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/hardware
        operator: Equal
        value: large-gpu
      - effect: PreferNoSchedule
        key: nvidia.com/gpu
        operator: Exists

      # Node affinity for V100 GPU
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - Tesla-V100-SXM2-32GB
                - Tesla-V100-SXM2-16GB
