apiVersion: batch/v1
kind: Job
metadata:
  name: v2v-diffusion-visualization-job-a100
spec:
  backoffLimit: 0  # Don't retry on failure
  template:
    metadata:
      labels:
        app: v2v-diffusion
        type: visualization-job
        gpu: a100
    spec:
      restartPolicy: Never

      containers:
      - name: visualization
        image: ghcr.io/kkuntal990/v2v-diffusion:latest
        imagePullPolicy: Always

        # Visualization command
        command: ["/bin/bash"]
        args:
        - "-c"
        - |
          echo "Starting visualization on Tesla V100-SXM2-32GB..."
          echo "GPU Info:"
          nvidia-smi
          echo ""
          echo "Node: $(hostname)"
          echo ""

          # Find the best checkpoint
          CHECKPOINT_DIR="/workspace/storage_a100/checkpoints/slice_interp_full_medium"

          # Check if checkpoint directory exists
          if [ ! -d "$CHECKPOINT_DIR" ]; then
            echo "ERROR: Checkpoint directory not found: $CHECKPOINT_DIR"
            exit 1
          fi

          # Look for best checkpoint
          if [ -f "$CHECKPOINT_DIR/checkpoint_best.pt" ]; then
            CHECKPOINT="$CHECKPOINT_DIR/checkpoint_best.pt"
            echo "Using best checkpoint: $CHECKPOINT"
          elif ls $CHECKPOINT_DIR/checkpoint_best_*.pt 1> /dev/null 2>&1; then
            CHECKPOINT=$(ls -t $CHECKPOINT_DIR/checkpoint_best_*.pt | head -1)
            echo "Using best checkpoint with suffix: $CHECKPOINT"
          elif ls $CHECKPOINT_DIR/checkpoint_epoch_*.pt 1> /dev/null 2>&1; then
            CHECKPOINT=$(ls -t $CHECKPOINT_DIR/checkpoint_epoch_*.pt | head -1)
            echo "Using latest epoch checkpoint: $CHECKPOINT"
          else
            echo "ERROR: No checkpoint found in $CHECKPOINT_DIR"
            exit 1
          fi

          # Generate visualizations for 10 validation samples
          echo ""
          echo "Generating visualizations for validation samples..."
          python scripts/visualize_samples.py \
            --checkpoint "$CHECKPOINT" \
            --config config/slice_interpolation_full_medium.yaml \
            --output-dir /workspace/storage_a100/visualizations \
            --split val \
            --num-samples 10 \
            --inference-steps 20

          echo ""
          echo "Visualization completed!"
          echo "Results saved to: /workspace/storage_a100/visualizations"
          echo ""
          echo "To download locally:"
          echo "  kubectl cp <pod-name>:/workspace/storage_a100/visualizations ./visualizations"
          sleep 360

        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
            nvidia.com/gpu: "1"
          limits:
            memory: "16Gi"
            cpu: "4"
            nvidia.com/gpu: "1"

        volumeMounts:
        - name: storage
          mountPath: /workspace/storage_a100
        - name: dshm
          mountPath: /dev/shm

        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TORCH_HOME
          value: "/workspace/storage_a100/.cache/torch"
        - name: HF_HOME
          value: "/workspace/storage_a100/.cache/huggingface"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: HF_TOKEN

      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: v2v-diffuser-kuntal-a100
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "16Gi"

      # Tolerations for V100 GPU nodes
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/hardware
        operator: Equal
        value: large-gpu
      - effect: PreferNoSchedule
        key: nvidia.com/gpu
        operator: Exists

      # Node affinity for Tesla V100-SXM2-32GB
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - Tesla-V100-SXM2-32GB
